export const DEFAULT_AUDIENCE_BODY = {
	description: "This was generated by the automation framework",
	status: "active",
	expression: JSON.stringify({ nodeType: "SEGMENT", segmentId: "1001697326" }),
};
