export const DEFAULT_USER_REQUEST_BODY = {
	lastName: "Test",
	phoneNumber: "155345654",
	email: "automation@test.com",
	timeZone: "Z",
	status: "active",
	publisherAccessRestrictionConfig: {
		accessRestriction: "all",
		blacklist: [],
		whitelist: [],
	},
	advertiserAccessRestrictionConfig: {
		accessRestriction: "all",
		blacklist: [],
		whitelist: [],
	},
	id: null,
	resetPassword: [],
};

export const DEFAULT_ROLE_REQUEST_BODY = {
	description: "This role was generated by the automation framework",
	permissions: [
		{
			id: 2,
			name: "VIEW_PUBLISHER_DASHBOARD",
			description: "Can view publisher dashboard.",
			enabled: true,
		},
	],
};
