export const bidderLocators = {
	addBidderButton: { locator: "Add Bidder", role: "link" },
	settingsTab: { locator: "Settings", role: "tab" },
	bidParametersTab: { locator: "Bid Parameters", role: "tab" },
	qualityTab: { locator: "Quality", role: "tab" },
	bidderNameField: { locator: "Bidder Name", role: "textbox" },
	statusActiveRadio: { locator: "Active", role: "radio" },
	statusInactiveRadio: { locator: "Inactive", role: "radio" },
	openRtbVersionDropdown: { locator: "OpenRTB Version 2.5", role: "button" },
	testModeToggle: { locator: "Test Mode", role: "checkbox" },
	multipleImpObjects: { locator: "Multiple Imp Objects", role: "checkbox" },
	companyAccessDropdown: { locator: "Company Access All", role: "button" },
	cookieSyncUrlField: { locator: "Cookie Sync URL", role: "textbox" },
	cookieSyncPercentageField: { locator: "Cookie Sync Percentage", role: "spinbutton" },
	matchedCookieBiddingToggle: { locator: "Matched Cookie Bidding", role: "checkbox" },
	bidUrlRegionDropdown: { locator: "Bid URL Region ​", role: "button" },
	bidUrlField: { locator: "Bid URL", role: "textbox" },
	addRegionButton: { locator: "Add Region", role: "button" },
	addSeatButton: { locator: "Add Seat", role: "button" },
	rtbMediaTypeDropdown: { locator: "RTB Media Type", role: "combobox" },
	compressBidRequestsToggle: { locator: "Compress Bid Requests", role: "checkbox" },
	demandFeePercentage: { locator: "Demand Fee Percentage", role: "spinbutton" },
	rtbFloorField: { locator: "RTB Floor", role: "spinbutton" },
	timeoutDurationField: { locator: "Timeout Duration", role: "spinbutton" },
	classOverrideField: { locator: "Class Override", role: "textbox" },
	omittedBidRequestParametersDropdown: { locator: "Omitted Bid Request Parameters", role: "combobox" },
	omittedSourceParametersDropdown: { locator: "Omitted Source Parameters", role: "combobox" },
	omittedImpressionsParameters: { locator: "Omitted Impression Parameters", role: "combobox" },
	omittedImpressionsParametersExp: { locator: "exp", role: "button" },
	omittedBannerParametersDropdown: { locator: "Omitted Banner Parameters", role: "combobox" },
	omittedVideoParametersDropdown: { locator: "Omitted Video Parameters", role: "combobox" },
	contentDeliveryTypeMultiselect: { locator: "Content Delivery Type", role: "combobox" },
	videoLinearityTypeLinearRadio: { locator: "Linear", role: "radio" },
	videLinearityTypeNonLinearRadio: { locator: "Non-Linear", role: "radio" },
	omittedDealParametersDropdown: { locator: "Omitted Deal Parameters", role: "combobox" },
	omittedSiteParametersDropdown: { locator: "Omitted Site Parameters", role: "combobox" },
	omittedPublisherParametersDropdown: { locator: "Omitted Publisher Parameters", role: "combobox" },
	omittedDeviceParametersDropdown: { locator: "Omitted Device Parameters", role: "combobox" },
	omittedGeoParametersDropdown: { locator: "Omitted Geo Parameters", role: "combobox" },
	omittedUserParametersDropdown: { locator: "Omitted User Parameters", role: "combobox" },
	useastOption: { locator: "us-east", role: "option" },
	uswestOption: { locator: "us-west", role: "option" },
	apacOption: { locator: "apac", role: "option" },
	allowListOption: { locator: "Allow List", role: "option" },
	companyAllowedListDropdown: "#companyAccessRestrictionConfig\\.whitelist",
	setttingsBadge: "#tab-SETTINGS > span.MuiBadge-root.BaseBadge-root > span",
	nameLabel: "#name-label",
	bidUrlRegionLabel: "#rtbUrls\\[0\\]\\.rtbRegionId-select-label",
	bidUrlLabel: "#rtbUrls\\[0\\]\\.url-label",
	nameHelper: "#name-helper-text",
	bidUrlRegionLabelHelper: "p.MuiFormHelperText-root.MuiFormHelperText-contained.Mui-error.Mui-required",
	bidUrlLabelHelper: "#rtbUrls\\[0\\]\\.url-helper-text",
};
