export default {
	ADD_MACRO_LABEL: "Add Macro",
	MACRO_OPTIONS: {
		ADVERTISER_GUID: { label: "Advertiser GUID", macro: "[adv_guid]" },
		ADVERTISING_DEVICE: { label: "Advertising Device ID", macro: "[adv_id]" },
		APP_ID: { label: "App ID", macro: "[app_id]" },
		APP_NAME: { label: "App Name", macro: "[app_name]" },
		APP_URI: { label: "App URI", macro: "[app_uri]" },
		APP_VERSION: { label: "App Version", macro: "[app_ver]" },
		CACHEBUSTER: { label: "Cachebuster", macro: "[cb]" },
		CAMPAIGN_GUID: { label: "Campaign GUID", macro: "[camp_guid]" },
		CHANNEL: { label: "Channel Name", macro: "[channel]" },
		CONNECTION_TYPE: { label: "Connection Type", macro: "[geo_conn_type]" },
		CONTENT_CATEGORY: { label: "Content Category", macro: "[content_cat]" },
		CONTENT_EPISODE: { label: "Content Episode", macro: "[content_episode]" },
		CONTENT_GENRE: { label: "Content Genre", macro: "[content_genre]" },
		CONTENT_LENGTH: { label: "Content Length", macro: "[content_len]" },
		CONTENT_LIVESTREAM: { label: "Content Livestream", macro: "[content_livestream]" },
		CONTENT_MEDIA_RATING: { label: "Content Media Rating", macro: "[content_qagmediarating]" },
		CONTENT_PRODUCTION_QUALITY: { label: "Content Production Quality", macro: "[content_prodq]" },
		CONTENT_SERIES: { label: "Content Series", macro: "[content_series]" },
		CONTENT_TITLE: { label: "Content Title", macro: "[content_title]" },
		CONTENT_LANGUAGE: { label: "Content Language", macro: "[content_language]" },
		COUNTRY: { label: "Country", macro: "[geo_co]" },
		DEVICE_MAKE: { label: "Device Make", macro: "[devicemake]" },
		DEVICE_MODEL: { label: "Device Model", macro: "[devicemodel]" },
		DEVICE_ID: { label: "Device ID", macro: "[device_id]" },
		DEVICE_TYPE: { label: "Device Type", macro: "[devicecategory]" },
		DMA: { label: "DMA", macro: "[geo_dma]" },
		DNT: { label: "Do Not Track", macro: "[dnt]" },
		IDFA_DEVICE: { label: "IDFA Device ID", macro: "[idfa]" },
		IP_ADDRESS: { label: "IP Address", macro: "[geo_ip]" },
		ISP: { label: "Internet Service Provider", macro: "[geo_isp_name]" },
		IO_GUID: { label: "IO GUID", macro: "[io_guid]" },
		LAT_LONG: { label: "Lat/Long", macro: "[geo_latlng]" },
		LATITUDE: { label: "Latitude", macro: "[geo_lat]" },
		LIMIT_AD_TRACKING: { label: "Limit Ad Tracking", macro: "[lmt]" },
		LONGITUDE: { label: "Longitude", macro: "[geo_long]" },
		MAX_DURATION: { label: "Max Duration", macro: "[max_ad_duration]" },
		MAXIMUM_AD_DURATION: { label: "Maximum Ad Duration", macro: "[pod_max_ad_dur]" },
		MEDIA_GUID: { label: "Media GUID", macro: "[media_guid]" },
		MINIMUM_AD_DURATION: { label: "Minimum Ad Duration", macro: "[pod_min_ad_dur]" },
		NETWORK: { label: "Network Name", macro: "[network]" },
		OPERATING_SYSTEM: { label: "Operating System", macro: "[osplatform]" },
		OS_MAJOR_VERSION: { label: "OS Major Version", macro: "[osvmajor]" },
		OS_MINOR_VERSION: { label: "OS Minor Version", macro: "[osvminor]" },
		OS_VERSION: { label: "OS Version", macro: "[osv]" },
		PAGE_DOMAIN: { label: "Page Domain", macro: "[page_domain]" },
		PAGE_URL: { label: "Page URL", macro: "[page_url]" },
		PLACEMENT_GUID: { label: "Placement GUID", macro: "[pla_guid]" },
		PLAYER_HEIGHT: { label: "Player Height", macro: "[player_height]" },
		PLAYER_WIDTH: { label: "Player Width", macro: "[player_width]" },
		POD_MAX_DURATION: { label: "Pod Max Duration", macro: "[pod_max_dur]" },
		POD_SIZE: { label: "Pod Size", macro: "[pod_size]" },
		POSTAL_CODE: { label: "Postal Code", macro: "[geo_code]" },
		PUBLISHER_GUID: { label: "Publisher GUID", macro: "[pub_guid]" },
		RANDOM_NUMBER: { label: "Random Number", macro: "[random_number]" },
		REFERRAL_DOMAIN: { label: "Referral Domain", macro: "[ref_page_domain]" },
		REFERRAL_URL: { label: "Referral URL", macro: "[ref_page_url]" },
		SITE_GUID: { label: "Site GUID", macro: "[site_guid]" },
		SSAI: { label: "SSAI", macro: "[ssai]" },
		STATE_CODE: { label: "State/Region Code", macro: "[geo_sub]" },
		STATE_NAME: { label: "State/Region Name", macro: "[geo_subname]" },
		TID: { label: "Transaction ID", macro: "[tid]" },
		TIMESTAMP: { label: "Timestamp", macro: "[timestamp]" },
		US_PRIVACY: { label: "US Privacy", macro: "[us_privacy]" },
		USER_ID: { label: "User ID", macro: "[cid]" },
		PLACEMENT: { label: "Placement", macro: "[plcmt]" },
		USER_ID_TYPE: { label: "User ID Type", macro: "[user_id_type]" },
		USER_AGENT: { label: "User Agent", macro: "[ua]" },
	},
};
