export const localeContent = {
	NOTIFICATION_NAME: "Name",
	SET_EXPIRATION: "Set Expiration",
	EXPIRES_IN: "Expires In",
};

export default {
	column: {
		name: { locator: "Name", role: "columnheader" },
		status: { locator: "Status", role: "columnheader" },
		type: { locator: "Type", role: "columnheader" },
		createdBy: { locator: "Created By", role: "columnheader" },
		createDate: { locator: "Create Date", role: "columnheader" },
		notificationDates: { locator: "Notification Date", role: "columnheader" },
		inactiveDate: { locator: "Inactive Date", role: "columnheader" },
		audienceSize: { locator: "Audience Size", role: "columnheader" },
	},
	addNotificationButton: { locator: "Add Notification", role: "link" },
	notificationNameField: { locator: "Name", role: "textbox" },
	notificationTextField: "div.ql-editor",
	notificationTypeField: { locator: "Notification Type", role: "combobox" },
	sendImmediatelyCheck: { locator: "Send Immediately", role: "checkbox" },
	forceNotification: { locator: "Force Notification", role: "checkbox" },
	notificationDateTime: { locator: /Choose date/i, role: "textbox" },
	OptimizationAlertOption: { locator: "Optimization Alert", role: "option" },
	setExpirationYes: { locator: "Set Expiration", role: "checkbox" },
	setExpireInDays: { locator: "Expires In", role: "spinbutton" },
	checkUserRole: { locator: "User Role", role: "checkbox" },
	checkCompany: { locator: "Company", role: "checkbox" },
	checkUser: { locator: "User", role: "checkbox" },
	roleAudienceSelection: { locator: "Role Audience Selection", role: "combobox" },
	selectCompanyAdminRole: { locator: "Company Admin", role: "option" },
	rteBold: ".ql-bold",
	rteItalic: ".ql-italic",
	rteUnderline: ".ql-underline",
	rteClean: ".ql-clean",
	rteList: ".ql-list",
	rteLink: ".ql-link",
	rtePicker: ".ql-picker",
};
