export const localeContent = {
	INDEX_HEADING: "Placements",
	SAVE_ALIGNMENTS: "Save Alignments",
	TOGGLE_ROW_SELECTED: "Toggle Row Selected",
	FIELD_NAMES: {
		placementName: "Placement Name",
		MULTIPLE_WINNERS: { LABEL: "Multiple Winners", OPTIONS: { YES: "Yes", NO: "No" } },
		TYPE: {
			LABEL: "Type",
			OPTIONS: {
				MOBILE: "Mobile App / CTV",
				DISPLAY: "Display",
				OUTSTREAM: "Outstream",
				VAST: "Instream",
			},
		},
		SIZE: "Size",
		SAVE_ALIGNMENTS: "Save Alignments",
		TOGGLE_ROW_SELECTED: "Toggle Row Selected",
		APP_ID_TARGETING: "App Bundle ID Targeting",
		APP_BUNDLE_ID: "Enter App Bundle ID",
		MULTIPLE_IMP_OBJECTS: "Multiple Imp Objects",
		CPM_PER_SECOND: "CPM Per Second",
		AUCTION_TYPE_FIRST_PRICE: "First Price",
		SERVER_SIDE_REQUEST: "Server-Side Requests",
		ALLOW_INVENTORY_PARTNER_DOMAIN: "Inventory Partner Domain",
		REQUEST_TYPE: {
			LABEL: "Request Type",
			OPTIONS: {
				TAG: "Tag",
				RTB: "RTB",
			},
		},
	},
	TEST_ID_FIELDS: {
		ALIGNMENTS_TABLE_AVALIABLE: "alignment-table-available",
		ALIGNMENTS_TABLE_ALIGN: "alignment-table-aligned",
	},
	TABS: {
		ALIGNMENTS: "Alignments",
		DEFAULTS: "Defaults",
	},
	VALIDATION_MESSAGES: {
		BIDDER_SERVICE_NOT_ENABLED_FOR_COMPANY: "The bidder service is not enabled for this company.",
	},
};

export default {
	addPlacementButton: { locator: "Add Placement", role: "link" },
	siteNameDropdown: { locator: "Site", role: "combobox" },
	placementNameField: { locator: localeContent.FIELD_NAMES.placementName, role: "textbox" },
	multipleImpObjectsField: { locator: localeContent.FIELD_NAMES.MULTIPLE_IMP_OBJECTS, role: "checkbox" },
	statusRadioActive: { locator: "Active", role: "radio" },
	statusRadioInactive: { locator: "Inactive", role: "radio" },
	revenueShareRadio: { locator: "Revenue Share (%)", role: "radio" },
	flatRateRadio: { locator: "Flat Rate ($)", role: "radio" },
	floorField: { locator: "Floor", role: "spinbutton" },
	revenueShareField: { locator: "Revenue Share", role: "spinbutton" },
	auctionFloorIncrementField: { locator: "Auction Floor Increment", role: "spinbutton" },
	auctionTypeFirstPriceRadio: { locator: "First Price", role: "radio" },
	auctionTypeSecondPriceRadio: { locator: "Second Price", role: "radio" },
	auctionMultipleWinnersField: { locator: "Multiple Winners", role: "radiogroup" },
	typeMobileDropDown: { locator: "Type Mobile App / CTV", role: "button" },
	typeInstreamDropDown: { locator: "Type Instream", role: "button" },
	typeDisplayDropDown: { locator: "Type Display", role: "button" },
	typeOutstreamDropDown: { locator: "Type Outstream", role: "button" },
	vastVersionDropDown: { locator: "VAST Version 4.0", role: "button" },
	supportVpaidRadioGroup: { locator: "Support VPAID", role: "radiogroup" },
	supportVpaidYesRadio: { locator: "Yes", role: "radio" },
	supportVpaidNoRadio: { locator: "No", role: "radio" },
	enableC6ManagerRadioGroup: { locator: "Enable C6 Ad Manager", role: "radiogroup" },
	enableC6AdManagerYesRadio: { locator: "Yes", role: "radio" },
	enableC6AdManagerNoRadio: { locator: "No", role: "radio" },
	defaultFormatDropDown: { locator: "Default Format Full Page", role: "button" },
	mobileFormatDropDown: { locator: "Mobile Format Dock to Top", role: "button" },
	audioToggle: { locator: "Audio", role: "checkbox" },
	setFrequencyCapToggle: { locator: "Set Frequency Cap", role: "checkbox" },
	browserBlacklistMultiSelect: { locator: "Browser Blacklist", role: "combobox" },
	pageElemetsBlacklistField: { locator: "Page Elements Blacklist", role: "combobox" },
	framebusterField: { locator: "Framebuster", role: "textbox" },
	viewUrlField: { locator: "View URL", role: "textbox" },
	clickUrlField: { locator: "Click URL", role: "textbox" },
	passbackField: { locator: "Passback", role: "textbox" },
	sizeDropDown: { locator: "Size", role: "combobox" },
	settingsTab: { locator: "Settings", role: "tab" },
	qualityTab: { locator: "Quality", role: "tab" },
	alignmentTab: { locator: "Alignments", role: "tab" },
	trackersMultiSelect: { locator: "Trackers", role: "combobox" },
	maxDurationField: { locator: "Max Duration", role: "spinbutton" },
	placementSkipField: { locator: "Placement Skip", role: "spinbutton" },
	limitAdResponseSizeToggle: { locator: "Limit Ad Response Size", role: "checkbox" },
	maxNumberOfAdsField: { locator: "Max Number of Ads", role: "textbox" },
	siteNameOptionZero: { locator: "Automation Entity", role: "option" },
	outstreamOption: { locator: "Outstream", role: "option" },
	mobileOption: { locator: "Mobile App / CTV", role: "option" },
	displayOption: { locator: "Display", role: "option" },
	instreamOption: { locator: "Instream", role: "option" },
	placementTagField: { locator: "Placement Tag", role: "textbox" },
	addFilterDropdown: { locator: "Add a filter", role: "button" },
	addDimensionDropdown: { locator: "Dimension ​", role: "button" },
	statusOptionSelect: { locator: "Status", role: "option" },
	saveButton: { locator: "Save", role: "button" },
	filterValue: "Value",
	filterStatusOptionActive: "Active",
	filterStatusOptionInactive: "Inactive",
	activeAlignedItemTitle: "Test Media Active",
	inactiveAlignedItemTitle: "Test Media Inactive",
	uploadButton: "[id='upload-button-appBundleIdBlacklistWhitelist']",
	addRestrictionButton: { locator: "add restriction", role: "button" },
	cloneAlignments: { locator: "Clone Alignments", role: "checkbox" },
};
