export const localeContent = {
	INDEX_HEADING: "Publishers",
};

export default {
	addPublisherButton: { locator: "Add Publisher", role: "link" },
	nameColumn: { locator: "Name", role: "columnheader" },
	nameColumnSort: { locator: "Name", role: "button" },
	nameSortAscending: { locator: "Name sorted ascending", role: "button" },
	nameSortDescending: { locator: "Name sorted descending", role: "button" },
	statusColumn: { locator: "Status", role: "columnheader" },
	statusSort: { locator: "Status", role: "button" },
	statusSortAscending: { locator: "Status sorted ascending", role: "button" },
	statusSortDescending: { locator: "Status sorted descending", role: "button" },
	opportunitiesColumn: { locator: "Opportunities", role: "columnheader" },
	opportunitiesSort: { locator: "Opportunities", role: "button" },
	opportunitiesSortAscending: { locator: "Opportunities sorted ascending", role: "button" },
	opportunitiesSortDescending: { locator: "Opportunities sorted descending", role: "button" },
	impressionsColumn: { locator: "Impressions", role: "columnheader" },
	impressionsSort: { locator: "Impressions", role: "button" },
	impressionsSortAscending: { locator: "Impressions sorted ascending", role: "button" },
	impressionsSortDescending: { locator: "Impressions sorted descending", role: "button" },
	revenueColumn: { locator: "Revenue ($)", role: "columnheader" },
	hideShowStatus: { locator: "Status", role: "checkbox" },
	hideShowOpportunities: { locator: "Opportunities", role: "checkbox" },
	hideShowImpressions: { locator: "Impressions", role: "checkbox" },
	hideShowRevenue: { locator: "Revenue ($)", role: "checkbox" },
	revenueSort: { locator: "Revenue ($)", role: "button" },
	revenueSortAscending: { locator: "Revenue ($) sorted ascending", role: "button" },
	revenueSortDescending: { locator: "Revenue ($) sorted descending", role: "button" },
	settingsTab: { locator: "Settings", role: "tab" },
	verificationTab: { locator: "Verification", role: "tab" },
	verificationTabMandatory: { locator: "Verification 1", role: "tab" },
	sitesTab: { locator: "Sites", role: "tab" },
	publisherNameField: { locator: "Publisher Name", role: "textbox" },
	statusActiveRadio: { locator: "Active", role: "radio" },
	statusInactiveRadio: { locator: "Inactive", role: "radio" },
	defaultFloorField: { locator: "Default Floor", role: "spinbutton" },
	revenueShareField: { locator: "Revenue Share", role: "spinbutton" },
	contactNameField: { locator: "Contact Name", role: "textbox" },
	contactEmailField: { locator: "Contact Email", role: "textbox" },
	phoneNumberField: { locator: "Phone Number", role: "textbox" },
	companyAddressField: { locator: "Company Address", role: "textbox" },
	billingDiffCheckbox: { locator: "Billing Different From Contact Info", role: "checkbox" },
	billingNameField: "#billing-name",
	billingEmailField: "#billing-email",
	billingPhoneField: "#billing-phone-number",
	billingAddressField: "#billing-address",
	publisherDomainField: { locator: "Publisher Domain", role: "textbox" },
	adSystemDomainField: { locator: "Ad System Domain", role: "textbox" },
	accountIdField: { locator: "Account ID", role: "textbox" },
	accountRelationshipRadioDirect: { locator: "Direct", role: "radio" },
	accountRelationshipRadioReseller: { locator: "Reseller", role: "radio" },
	certificationAuthorityIdField: { locator: "Certification Authority ID", role: "textbox" },
	sellerTypeRadioPublisher: { locator: "Publisher", role: "radio" },
	sellerTypeRadioIntermediary: { locator: "Intermediary", role: "radio" },
	sellerTypeRadioBoth: { locator: "Both", role: "radio" },
	isConfidentialRadioYes: { locator: "Yes", role: "radio" },
	isConfidentialRadioNo: { locator: "No", role: "radio" },
	setttingsBadge: "#tab-SETTINGS > span.MuiBadge-root.BaseBadge-root > span",
	verificationBadge: "#tab-VERIFICATION > span.MuiBadge-root.BaseBadge-root > span",
	nameLabel: "#name-label",
	contactNameLabel: "#contactName-label",
	contactEmailLabel: "#contactEmail-label",
	contactPhoneLabel: "#contactPhone-label",
	contactAddressLabel: "#contactAddress-label",
	nameHelper: "#name-helper-text",
	contactNameHelper: "#contactName-helper-text",
	contactEmailHelper: "#contactEmail-helper-text",
	contactPhoneHelper: "#contactPhone-helper-text",
	contactAddressHelper: "#contactAddress-helper-text",
	domainLabel: "#webSiteDomain-label",
	domainHelperText: "#webSiteDomain-helper-text",
	tmaxField: { locator: "Tmax (milliseconds)", role: "spinbutton" },
	gridClass: ".MuiDataGrid-virtualScrollerRenderZone",
	selectColumns: { locator: "Select columns", role: "button" },
};
