export const localeContent = {
	REPORTING: "Reporting",
	VALUES: "Values",
	COUNTRY_INDIA: "India",
	STATUS_PENDING: "Pending",
	STATUS_FINISHED: "Finished",
	MY_REPORTS: "My Reports",
	OPTION_DEAL: "Deal",
	METRIC_LABEL: {
		OPPORTUNITIES: "Opportunities",
		IMPRESSIONS: "Impressions",
		FILL_RATE: "Fill Rate",
		POTENTIAL_FILL_RATE: "Potential Fill Rate",
		GROSS_CPM: "Gross CPM",
		GROSS_REVENUE: "Gross Revenue",
		RTB_OPPORTUNITIES: "Requests Sent",
		RTB_BIDS: "Bids",
		WINS: "Wins",
		BID_RATE: "Bid Rate",
		WIN_RATE: "Win Rate",
		CLOSE_RATE: "Close Rate",
		CLOSE_CPM: "Close CPM",
		CLOSE_REVENUE: "Close Revenue",
		QUARTILE_0: "Quartile 0",
		QUARTILE_25: "Quartile 25",
		QUARTILE_50: "Quartile 50",
		QUARTILE_75: "Quartile 75",
		QUARTILE_100: "Quartile 100",
		PUBLISHER_CPM: "Publisher CPM",
		PUBLISHER_REVENUE: "Publisher Revenue",
		NET_MARGIN: "Net Margin",
		NET_REVENUE: "Net Revenue",
		CLICKS: "Clicks",
		CTR: "CTR",
		VIEWABLE: "Viewabilty",
		DEMAND_OPPORTUNITIES: "Demand Opportunities",
		DEMAND_PARTNER_FEE: "Demand Partner Fees",
		AD_ATTEMPTS: "Ad Attempts",
		BID_CPM: "Bid CPM",
		BID_REVENUE: "Bid Revenue",
		BID_ERRORS: "Bid Errors",
		TCP_ERRORS: "TCP Errors",
		TIMEOUTS: "Timeouts",
		MOAT_VREVENUE: "Moat vRevenue",
		MOAT_VCPM: "Moat vCPM",
		MOAT_VIEWABILITY: "Moat Viewability",
		MOAT_AUDIBILITY: "Moat Audibility",
		BID_REQUEST_COST: "Bid Request Cost",
		OPPORTUNITY_COST: "Opportunity Cost",
		OPPORTUNITY_COST_PERCENT: "Opportunity Cost %",
		POTENTIAL_BID_REQUESTS: "Potential Bid Requests",
		FILTERED_REQUESTS: "Filtered Requests",
	},
	DEMAND_CLIENT_METRIC_LABELS: {
		GROSS_REVENUE: "Gross Spend",
	},
	METRIC_TOOL_TIP: {
		BID_REQUESTS: "The number of impressions that were available to be bid on",
	},
	RUN_REPORT_BUTTON: "Run Report",
	TAB_LABEL_CAMPAIGN: "Campaign",
	TAB_LABEL_RTB: "RTB",
	ADD_DIMENSION_BUTTON_LABEL: "Add Dimension",
	ADD_FILTER_BUTTON_LABEL: "Add A Filter",
	FIELD_LABEL_DIMENSION: "Dimension",
	FIELD_LABEL_SELECTED_DIMENSIONS: "Dimensions",
	FIELD_SLICES: {
		LABEL: "Slices",
	},
	ADD_SLICE_BUTTON: "add item",
	SLICE_LABELS: {
		publisher: "Publisher",
		site: "Site",
		placement: "Placement",
		seatId: "Seat ID",
		dealid: "Deal Id",
		buyers: "Buyers",
		appName: "App Name",
		appBundle: "App Bundle",
		domain: "Domain",
		hour: "Hour",
		podSequence: "Pod Sequence",
		contentGenre: "Content Genre",
	},
	EXPORT_BUTTON_LABEL: "Export",
	ADD_FILTER_BUTTON: "Add a filter",
	FILTER_DIMENSION_LABEL: "Dimension",
	FILTER_DIMENSION_OPTIONS_LABEL: "Values",
	FILTER_SAVE_BUTTON: "Save",
	METRICS_MENU_BUTTON: "select metrics",
	METRICS_MENU_SHOW_ALL_BUTTON: "Show all",
	SCHEDULE_REPORTS_BUTTON: "Schedule",
	SCHEDULE_REPORTS_TAB_LABEL: {
		DATA: "Data",
	},
	SCHEDULE_REPORTS_DIMENSIONS_LABEL: "Dimensions",
	SELECTED_SLICES_LIST: "selected options",
	SUCCESS_MESSAGE_ON_REPORT_SAVE: (reportName) =>
		`Successfully saved ${reportName}. Click here to access the report `,
	REPORT_NAME: {
		MODAL_REPORT_NAME: "Report Name",
	},
	ACTION_BUTTON_DOWNLOAD_CSV: "Download CSV (triggers download)",
	ACTION_BUTTON_DOWNLOAD_EXCEL: "Download Excel (triggers download)",
};

export default {
	previous7Days: { locator: "Previous 7 Days", role: "button" },
	dateRangeTabCustom: { locator: "Custom", role: "tab" },
	addFilterDropdown: { locator: "Add a filter", role: "button" },
	addDimensionDropdown: { locator: "Dimension ​", role: "button" },
	countryOptionSelect: { locator: "Country", role: "option" },
	saveButton: { locator: "Save", role: "button" },
	enableSlice: { locator: "Slices", role: "checkbox" },
	addSliceButton: { locator: "add item", role: "button" },
	openMetricsOptions: { locator: "select metrics", role: "button" },
	checkPublisherCPM: { locator: "Publisher CPM ($)", role: "checkbox" },
	runReportButton: { locator: "Run Report", role: "button" },
	exportButton: { locator: "Export", role: "button" },
	downloadCSVButton: { locator: localeContent.ACTION_BUTTON_DOWNLOAD_CSV, role: "menuitem" },
	downloadExcelButton: { locator: localeContent.ACTION_BUTTON_DOWNLOAD_EXCEL, role: "menuitem" },
	UNSAVED_CHANGES_INDICATOR_BADGE_TEST_ID: "submit-button-with-badge-unapplied-changes-indicator",
	TEST_ID_DIMENSIONS_TOOLBAR_CHIP: "dimensions-toolbar-chip",
	networkTab: { locator: "Network", role: "tab" },
	campaignTab: { locator: "Campaign", role: "tab" },
	rtbTab: { locator: "RTB", role: "tab" },
	sliceSelectionButton: { locator: "Add Dimension", role: "button" },
	sliceOptionCityButton: { locator: "City", role: "menuitem" },
	sliceOptionPublisherButton: { locator: "Publisher", role: "menuitem" },
	sliceOptionDaysMenuItem: { locator: "Day", role: "menuitem" },
	sliceOptionHoursMenuItem: { locator: "Hour", role: "menuitem" },
	sliceOptionAppBundleMenuItem: { locator: "App Bundle", role: "menuitem" },
	selectMetricsButton: { locator: "select metrics", role: "button" },
	showAllButton: { locator: "Show all", role: "button" },
	dataRowIndexAttribute: "data-rowindex",
	dateRange: { locator: /Date Range/i, role: "button" },
	firstDateOfTheMonth: { locator: "1", role: "gridcell" },
	relativeTab: { locator: "Relative", role: "tab" },
	customTab: { locator: "Custom", role: "tab" },
	dateRangeButtonPrevious30Days: { locator: "Previous 30 Days", role: "button" },
	dateRangeButtonPrevious7Days: { locator: "Previous 7 Days", role: "button" },
	dateRangeButtonPreviousMonth: { locator: "Previous Month", role: "button" },
	dateRangeButtonMonthToDate: { locator: "Month to Date", role: "button" },
	dateRangeButtonToday: { locator: "Today", role: "button" },
	timeZoneTestId: "timeZoneChip",
	timeZoneCTButton: { locator: "Central Time", role: "button" },
	timeZoneUTCButton: { locator: "Coordinated Universal Time (UTC)", role: "button" },
	notAvailable: "Not Available",
	notProvided: "Not Provided",
	replaceValue: "[REPLACE]",
	nullValue: "null",
	previousMonthClickFromCalendarLeftArrow: { locator: "Previous month", role: "button" },
	twentiethDateOfTheMonth: { locator: "20", role: "gridcell" },
	addDimensionButton: { locator: "Add Dimension", role: "button" },
	quartile0MetricsCheckbox: { locator: "Quartile 0", role: "checkbox" },
	quartile25MetricsCheckbox: { locator: "Quartile 25", role: "checkbox" },
	quartile50MetricsCheckbox: { locator: "Quartile 50", role: "checkbox" },
	quartile75MetricsCheckbox: { locator: "Quartile 75", role: "checkbox" },
	quartile100MetricsCheckbox: { locator: "Quartile 100", role: "checkbox" },
	modalReportNameMTextBox: { locator: "Report Name", role: "textbox" },
	modalSaveButton: { locator: "Save", role: "button" },
};
