export const localeContent = {};

export default {
	navigationMenuButtonReporting: { locator: "reporting menu", role: "button" },
	navigationMenuButtonSupply: { locator: "supply menu", role: "button" },
	navigationMenuButtonDemand: { locator: "demand menu", role: "button" },
	navigationMenuButtonAdmin: { locator: "admin menu", role: "button" },
	navigationMenuButtonCompanyMenu: { locator: "company menu", role: "button" },
	dashboardButton: { locator: "Dashboard", role: "button" },
	myReportsButton: { locator: "My Reports", role: "button" },
	publisherDashboardButton: { locator: "Publisher Dashboard", role: "button" },
	publishersButton: { locator: "Publishers", role: "link" },
	sitesButton: { locator: "Sites", role: "link" },
	placementsButton: { locator: "Placements", role: "link" },
	advertisersButton: { locator: "Advertisers", role: "link" },
	insertionsButton: { locator: "Insertions", role: "link" },
	campaignsButton: { locator: "Campaigns", role: "link" },
	mediaButton: { locator: "Media", role: "link" },
	programmaticButton: { locator: "Programmatic", role: "link" },
	usersButton: { locator: "Users", role: "link" },
	rolesButton: { locator: "Roles", role: "link" },
	companiesButton: { locator: "Companies", role: "link" },
	biddersButton: { locator: "Bidders", role: "link" },
	notificationsAdminButton: { locator: "Notifications", role: "button" },
	audiencesButton: { locator: "Audiences", role: "link" },
	dataDistributionsButton: { locator: "Data Distributions", role: "button" },
	trackersButton: { locator: "Trackers", role: "button" },
	navigationItemGlobalBlocklist: { locator: "Global Blocklist", role: "link" },
	userSettingsButton: { locator: "user settings menu", role: "link" },
	notificationsButton: { locator: "notifications", role: "button" },
	helpButton: { locator: "help menu", role: "button" },
	logoutButton: { locator: "Logout", role: "button" },
	activeCompanyDropdown: { locator: "Active Company", role: "combobox" },
	collapseLinkClick: { locator: "Collapse", role: "button" },
};
