export const localeContent = { FIELDS: { FIRST_NAME: "First Name", LAST_NAME: "Last Name" } };

export const userLocators = {
	addUserButton: { locator: "Add User", role: "link" },
	firstNameField: { locator: "First Name", role: "textbox" },
	lastNameField: { locator: "Last Name", role: "textbox" },
	phoneNumberField: { locator: "Phone Number", role: "textbox" },
	emailAddressField: { locator: "Email Address", role: "textbox" },
	timeZoneDropdown: { locator: "Timezone", role: "combobox" },
	statusActiveRadio: { locator: "Active", role: "radio" },
	statusInactiveRadio: { locator: "Inactive", role: "radio" },
	rolesDropdown: { locator: "Roles", role: "combobox" },
	publisherAccessDropdownAllowAll: { locator: "Publisher Access Allow All", role: "button" },
	publisherAccessDropdownBlockAll: { locator: "Publisher Access Block All", role: "button" },
	publisherAccessDropdownBlockList: { locator: "Publisher Access Block List", role: "button" },
	publisherAccessDropdownAllowList: { locator: "Publisher Access Allow List", role: "button" },
	advertiserAccessDropdownAllowAll: { locator: "Advertiser Access Allow All", role: "button" },
	advertiserAccessDropdownBlockAll: { locator: "Advertiser Access Block All", role: "button" },
	advertiserAccessDropdownBlockList: { locator: "Advertiser Access Block List", role: "button" },
	advertiserAccessDropdownAllowList: { locator: "Advertiser Access Allow List", role: "button" },
	publisherBlockListDropdown: { locator: "Publisher Block List", role: "combobox" },
	advertiserBlockListDropdown: { locator: "Advertiser Block List", role: "combobox" },
	publisherAllowListDropdown: { locator: "Publisher Allow List", role: "combobox" },
	advertiserAllowListDropdown: { locator: "Advertiser Allow List", role: "combobox" },
	allowAllOption: { locator: "Allow All", role: "option" },
	blockAllOption: { locator: "Block All", role: "option" },
	blockListOption: { locator: "Block List", role: "option" },
	allowListOption: { locator: "Allow List", role: "option" },
	roleOptionZero: "#roles-option-0",
};
